#!/usr/bin/env bash

WALLDIR="$HOME/.config/hypr/walls"


swww init 2>/dev/null


WALL=$(find "$WALLDIR" -type f | shuf -n 1)


swww img "$WALL" --transition-step=90


matugen image "$WALL"
